apiVersion: v1
kind: Service
metadata:
  name: mindglow-authentication-server-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30001
  selector:
    app: mindglow-authentication-server
  