apiVersion: apps/v1
kind: Deployment
metadata:
  name: mindglow-subject-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mindglow-subject-server
  template:
    metadata:
      labels:
        app: mindglow-subject-server
    spec:
      containers:
        - name: subject-server
          image: xemii16/mindglow-subject-server:0.2.21
          ports:
            - containerPort: 8081
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
            - name: LOGGING_LEVEL_APPLICATION
              value: debug
            - name: LOGGING_LEVEL_ROOT
              value: debug
            - name: SPRING_PROFILES_ACTIVE
              value: demonstration, kubernetes
            - name: RSA_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: rsa-key-pair
                  key: public-key
            - name: RSA_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: rsa-key-pair
                  key: private-key
            - name: KEY_ALGORITHM
              value: "RSA"
            - name: POSTGRES_HOST
              value: "postgres"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DATABASE
              value: "mindglow"
            - name: POSTGRES_USERNAME
              value: "user"
            - name: POSTGRES_PASSWORD
              value: "password"