apiVersion: apps/v1
kind: Deployment
metadata:
  name: mindglow-web-bff-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mindglow-web-bff-server
  template:
    metadata:
      labels:
        app: mindglow-web-bff-server
    spec:
      containers:
        - name: authentication-server
          image: xemii16/mindglow-web-bff:0.1.26-TEST
          ports:
            - containerPort: 8082
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
            - name: SPRING_DATA_MONGODB_HOST
              value: "mongodb"
            - name: SPRING_DATA_MONGODB_PORT
              value: "27017"
            - name: SPRING_DATA_MONGODB_USER
              value: "root"
            - name: SPRING_DATA_MONGODB_PASSWORD
              value: "example"