apiVersion: v1
kind: Service
metadata:
  name: mindglow-subject-server-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      nodePort: 30002
  selector:
    app: mindglow-subject-server
  