apiVersion: v1
kind: Service
metadata:
  name: mindglow-web-bff-server-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8082
      targetPort: 8082
      nodePort: 30003
  selector:
    app: mindglow-web-bff-server
