apiVersion: apps/v1
kind: Deployment
metadata:
  name: mindglow-web-bff-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mindglow-web-bff-server
  template:
    metadata:
      labels:
        app: mindglow-web-bff-server
    spec:
      containers:
        - name: authentication-server
          image: xemii16/mindglow-web-bff:0.3.2
          ports:
            - containerPort: 8082
          env:
            - name: MINDGLOW_SUBJECT_SERVICE_URI
              value: "http://mindglow-subject-server-service:8081"
            - name: MINDGLOW_AUTHENTICATION_SERVICE_URI
              value: "http://mindglow-authentication-server-service:8080"
            - name: CORS_ALLOWED_ORIGINS
              value: "http://localhost:4200"
            - name: CORS_ALLOWED_METHODS
              value: "GET,OPTIONS,POST,PUT,PATCH,DELETE"
            - name: CORS_ALLOWED_HEADERS
              value: "Authorization,Content-Type,Cache-Control"
            - name: CORS_ALLOW_CREDENTIALS
              value: "true"
            - name: LOGGING_LEVEL_APPLICATION
              value: "error"
            - name: RSA_PRIVATE_KEY
              valueFrom:
                  secretKeyRef:
                    name: rsa-key-pair
                    key: private-key
            - name: RSA_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: rsa-key-pair
                  key: public-key
            - name: JAVA_TOOL_OPTIONS
              value: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
            - name: SPRING_DATA_MONGODB_HOST
              value: "mongodb"
            - name: SPRING_DATA_MONGODB_PORT
              value: "27017"
            - name: SPRING_DATA_MONGODB_USERNAME
              value: "user"
            - name: SPRING_DATA_MONGODB_PASSWORD
              value: "password"
            - name: SPRING_DATA_MONGODB_DATABASE
              value: "bff"