apiVersion: apps/v1
kind: Deployment
metadata:
  name: mindglow-authentication-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mindglow-authentication-server
  template:
    metadata:
      labels:
        app: mindglow-authentication-server
    spec:
      containers:
        - name: authentication-server
          image: xemii16/mindglow-authentication-server:0.2.6
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: demonstration, kubernetes
            - name: RSA_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: rsa-key-pair
                  key: private-key
            - name: RSA_PUBLIC_KEY
              valueFrom:
                  secretKeyRef:
                    name: rsa-key-pair
                    key: public-key
            - name: KEY_ALGORITHM
              value: "RSA"
            - name: TOKEN_EXPIRATION_REFRESH
              value: "432000"
            - name: TOKEN_EXPIRATION_ACCESS
              value: "300"
            - name: TOKEN_ALGORITHM
              value: "RSA"
            - name: POSTGRES_HOST
              value: "postgres"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DATABASE
              value: "mindglow"
            - name: POSTGRES_USERNAME
              value: "user"
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: LOGGING_LEVEL_APPLICATION
              value: trace
            - name: JAVA_TOOL_OPTIONS
              value: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/mindglow
            - name: SPRING_DATASOURCE_USERNAME
              value: user
            - name: SPRING_DATASOURCE_PASSWORD
              value: password