apiVersion: v1
kind: Secret
metadata:
  name: rsa-key-pair
type: Opaque
stringData:
  private-key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEAjLLG4k5jXVPv9RHG4KWc5XnBZT08w2hs9CMQH9H9zPnM0gcV
    ApjJGSYGU6mo9oF1czEr8eBKvCpu1EtNa7Lcs39bkU2swT5vUBDygVec3YWLhOFp
    dTv0mstKL/vpkZf0vhDR/5Cr61SBUWISS/IwVjpnSGeq8HqcGYBZSNwmuFRp+WX8
    cjngP6ISoqLKfqRrbHlVN2mn9MD7A6zCkqN17ugIHsL4uHqQULzhzuq8unH+h17Z
    2FOuGhhQpgYbIjskpyu0sDnDVBTbDmh2UTKCUixcUCAkny3hGWaLMhAwshrce1Zl
    +5AksgK28IEQV/yAiLSNBNB3tsEoLCAWwY1QYwIDAQABAoIBAQCBEixDRTgAUNUr
    k9BHG4awOR7CWggZFv4EhPnwxvo2hN5xug97H2A0Et7w9w5KfP6a2vv+Ww0USzT6
    yc3PQ/kVLXt587DMYhNJdxKQtyfvS+hu0T6mTocZTe7T0Bw39RePGO0crsIYE6DC
    YN56D0ZqhA9lq7xz+XakKks9/MAEjfrOeom7hj3XXO6fHwM8b8Y0d16639DHWOdv
    mfjorkJ1nDw0HdA2NnLsbqpVemuEVfSjgoJReVVyp68sYqhp/+tTrpDnp4nzdR4g
    1wrQp9TKJxRTGaFBqmeCKUbniwZ9fhiXZAsfQ2pTCE8ig3Dwn54o7OIAJmCPzNWv
    hkiYnlDBAoGBAPjS6Q7AHgm22PbfD54rFx1FfLgw5S4q2722iLNVyosibn2fqtp3
    p9hZVrqXuko+WEPsatIg7qLM8MgHud6kLd4/QP82+tquoOqPWXWlBJrLM0KuBRBB
    ipPslfDbLjLxz4E6i3rXdM2lIqV0JBaYBdZl/7o/ImlFAhlcW9v3+Y5DAoGBAJDB
    kNe3G5tFpShVZg2SlqqDZb2CYfhAv5LK+36wrMXoQ6j5a5VqW52EBhvjc25bABzI
    JvHZ6YSA31wljEL6mWlKMQ7xhZYH81Nu19YfdJ7lsdBHTWva80sCcZEIMIOqYTnA
    sbMydEjZAlhakHmh6ojEVq6IEokaD/Ahbq8us+NhAoGASTU0oMRhkhYcC7ZhT/X5
    nQEeysqIA2dUs6KK4ciyCPGedJOPnytpVLwkSk3t334sVf+vBhfuXjPR++haBWlk
    nWka5Hv2nnSWn6yBc52Tlz+F2257yuadsRwAmZbDJvYCSVFCTGgr031sjiV3oLYl
    sYjdDp0YsMQ+89s6o6N35yUCgYA8TKWtdlVFpQlbd9d/J+UjOoETJFDzPOWQnIWP
    DMGr30jwBpZOM3PedbSlwWXAPqAZXTb74C5qR9TDadC3xfRJ6+Hru6hOCxnNU4sN
    YyUNW9lqTYluuFJImMf+Bk9PSZYenKppX0cZYWycqX0tbclpF4CUS5KNEhI5kXOt
    /eJpgQKBgD0T/Qb7iSoVscbQ5uUw6eEJQpwAWA9F7oLuera6ln7I8iW7ou3bPRLj
    GUx+RllQQgwrp5bO8pBBlUHLcbeElWs5jQLYBPn95CtqzwDZSFgfnm5zcZfrIENj
    WRe9aJHCQxxNT3RDLj8VzCGSmONMh68iO41jdeHZZK3L2HXnJQAD
    -----END RSA PRIVATE KEY-----
  public-key: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjLLG4k5jXVPv9RHG4KWc
    5XnBZT08w2hs9CMQH9H9zPnM0gcVApjJGSYGU6mo9oF1czEr8eBKvCpu1EtNa7Lc
    s39bkU2swT5vUBDygVec3YWLhOFpdTv0mstKL/vpkZf0vhDR/5Cr61SBUWISS/Iw
    VjpnSGeq8HqcGYBZSNwmuFRp+WX8cjngP6ISoqLKfqRrbHlVN2mn9MD7A6zCkqN1
    7ugIHsL4uHqQULzhzuq8unH+h17Z2FOuGhhQpgYbIjskpyu0sDnDVBTbDmh2UTKC
    UixcUCAkny3hGWaLMhAwshrce1Zl+5AksgK28IEQV/yAiLSNBNB3tsEoLCAWwY1Q
    YwIDAQAB
    -----END PUBLIC KEY-----