spring:
  main:
    cloud-platform: kubernetes
  application:
    name: web-bff
  session:
    mongodb:
      collection-name: sessions
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
server:
  port: 8082
